#!/usr/bin/env node
// Build a single-file, dependency-free copy of the game: dist/dusk-circuit-standalone.html
// - src/ modules are concatenated in dependency order (relative imports/exports stripped)
// - three.js comes from a CDN via the import map (pinned to package.json's version)
// - .glb assets are inlined as base64 and served through globalThis.__DUSK_INLINE_ASSETS
// This is not a bundler for the repo (the site runs from ES modules as-is); it exists so the
// game can be handed around as one file, e.g. published as a Claude artifact.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, normalize, relative, resolve } from 'node:path';

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), '..');
const THREE_VERSION = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).dependencies.three;
const CDN = process.env.THREE_CDN || `https://cdn.jsdelivr.net/npm/three@${THREE_VERSION}`;
const args = process.argv.slice(2);
const FRAGMENT = args.includes('--fragment'); // no <!doctype>/<html>/<head>/<body>: for hosts that wrap the page themselves
const out = args.find((a) => !a.startsWith('--')) || join(ROOT, 'dist', FRAGMENT ? 'dusk-circuit-fragment.html' : 'dusk-circuit-standalone.html');

// --- module graph ---------------------------------------------------------
const order = [];
const seen = new Set();
const externalImports = new Set();
function visit(file) {
  const key = normalize(file);
  if (seen.has(key)) return;
  seen.add(key);
  const src = readFileSync(key, 'utf8');
  for (const m of src.matchAll(/^import\s[^;]*?from\s+'([^']+)';?$/gm)) {
    const spec = m[1];
    if (spec.startsWith('.')) visit(join(dirname(key), spec));
    else externalImports.add(m[0].replace(/;?$/, ';'));
  }
  order.push(key);
}
visit(join(ROOT, 'src', 'main.js'));

function strip(src) {
  return src
    .replace(/^import\s[^;]*?from\s+'[^']+';?\s*$/gm, '')
    .replace(/^export\s*\{[^}]*\}\s*from\s+'[^']+';?\s*$/gm, '')
    .replace(/^export\s*\*\s*as\s+\w+\s+from\s+'[^']+';?\s*$/gm, '')
    .replace(/^export\s*\{[^}]*\};?\s*$/gm, '')
    .replace(/^export\s+(default\s+)?/gm, '');
}
const body = order.map((f) => `// ---- ${relative(ROOT, f)} ----\n${strip(readFileSync(f, 'utf8'))}`).join('\n');

// --- assets ---------------------------------------------------------------
const assetFiles = ['assets/track.glb', ...['ember', 'tideglass', 'ironmoth', 'nightjar'].map((n) => `assets/karts/${n}.glb`)];
const inline = {};
for (const a of assetFiles) inline[`./${a}`] = readFileSync(join(ROOT, a)).toString('base64');

// --- page -----------------------------------------------------------------
let html = readFileSync(join(ROOT, 'index.html'), 'utf8');
html = html.replace(/<script type="importmap">[\s\S]*?<\/script>/, `<script type="importmap">
    { "imports": { "three": "${CDN}/build/three.module.js", "three/addons/": "${CDN}/examples/jsm/" } }
  </script>`);
html = html.replace(
  '<script type="module" src="./src/main.js"></script>',
  `<script>globalThis.__DUSK_INLINE_ASSETS = ${JSON.stringify(inline)};</script>\n  <script type="module">\n${[...externalImports].join('\n')}\n${body}\n  </script>`
);
html = html.replace('<title>Dusk Circuit</title>', '<title>Dusk Circuit</title>\n  <!-- Single-file build generated by tools/build_artifact.mjs. Source: https://github.com/icomppower/mariokarttest -->');
if (FRAGMENT) {
  const head = html.match(/<head>([\s\S]*?)<\/head>/)[1].replace(/\s*<meta[^>]*>/g, '');
  const bodyHtml = html.match(/<body>([\s\S]*?)<\/body>/)[1];
  html = `${head.trim()}\n${bodyHtml.trim()}\n`;
}
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, html);
console.log(`${relative(ROOT, out)}: ${(html.length / 1e6).toFixed(2)} MB, ${order.length} modules, ${assetFiles.length} assets inlined, three@${THREE_VERSION} from ${CDN}`);
